### ISSUE TITLE
Setup project structure

### ISSUE THREAD

**Issue by being-curious** [plannifnminus1fails/destiny#1]
As a developer, I need to create a basic folder structure for this project so that other developers can use that as a start point.
# Tasks
- [x] Create an application with mean.io boilerplate.
- [x] Install admin, tokens, translate, ga, upload, sockets and comments packages.
- [x] Configure these packages.
- [x] Test at localhost.
- [x] Push to "destiny" repo at github.
