### ISSUE TITLE
Set up Jenkins for the Destiny repo

### ISSUE THREAD

**Issue by scrock1987** [plannifnminus1fails/destiny#13]
We need to setup a CI environment for our Repo.
# Tasks:
- [x] Install Jenkins on the server machine.
- [x] Configure Destiny project build on it.
- [ ] Publish Jenkins Setup wiki
