### ISSUE TITLE
As a visitor, I shall be able to view all the products.

### ISSUE THREAD

**Issue by being-curious** [plannifnminus1fails/destiny#5]
# Parent issue #8

The user must be able to see the Product listing page.
# Tasks
- [x] Create service routes for displaying the products.
- [x] Create Service for fetching the products as a JSON.
- [x] Display all the products on the UI
