### ISSUE TITLE
As an administrator, I should be able to add products

### ISSUE THREAD

**Issue by being-curious** [plannifnminus1fails/destiny#6]
# Parent Issue #8
# Tasks
- [x] Setup product package structure
  - Copy article package & replace all instance of `article` with `product`
- [x] Finalize Product schema
  - https://github.com/plannifnminus1fails/destiny/issues/20
- [x] Add attributes to product schema as per finalized product schema
  - Replace all instance of `content` with `description` as we need `description` attribute instead of `content`
  - Add remaining attributes to model at `packages/custom/products/server/models/products.js`
- [x] Update AngularJS views at `/packages/custom/products/public/views`
- [x] Update AngularJS controller at `/packages/custom/products/public/controllers/products.js`
