### ISSUE TITLE
Search bar should be working properly

### ISSUE THREAD

**Issue by scrock1987** [plannifnminus1fails/destiny#82]
## Tasks:
- [x]  Find/create/update web service that will search products based on input
- [x]  Create a controller that will manage search box
- [x]  Result must will be displayed on product listing page; It means we have to use listing view.
