### ISSUE TITLE
Fix cart functionality

### ISSUE THREAD

**Issue by scrock1987** [plannifnminus1fails/destiny#98]
## Tasks:  
  - [x] Fix cart totalling and sub total values.
  - [x] Make update cart working available.
  - [x] Cart must have a delete button for each row of items.
  - [x] Place order should direct you to order management.
  - [x] Continue shopping button redirects you to HOMEPAGE
